"""Play back Synology Surveillance Station recordings (and time-lapse) as HLS."""

from .client import (
    OTP_ERRORS,
    Bookmark,
    Camera,
    RecordingInfo,
    SSAuthError,
    SSConnectionError,
    SSError,
    SSInfo,
    SurveillanceStationClient,
    TimelapseRecording,
)
from .segment import (
    drain_transcodes,
    fetch_segment,
    fetch_snapshot,
    fetch_timelapse_segment,
    recordings_from,
    remove_stale_temp_files,
)
from .timelapse import (
    CODECS,
    TimelapseRun,
    TranscodeSpec,
    broken_frames,
    covered,
    hardware_transcode_available,
    output_size,
    plan_day,
    slice_types,
)
from .vod import (
    Recording,
    Run,
    Segment,
    live_edge,
    plan_segments,
    render_playlist,
    runs_from_segments,
)

__all__ = [
    "CODECS",
    "OTP_ERRORS",
    "Bookmark",
    "Camera",
    "Recording",
    "RecordingInfo",
    "Run",
    "SSAuthError",
    "SSConnectionError",
    "SSError",
    "SSInfo",
    "Segment",
    "SurveillanceStationClient",
    "TimelapseRecording",
    "TimelapseRun",
    "TranscodeSpec",
    "broken_frames",
    "covered",
    "drain_transcodes",
    "fetch_segment",
    "fetch_snapshot",
    "fetch_timelapse_segment",
    "hardware_transcode_available",
    "live_edge",
    "output_size",
    "plan_day",
    "plan_segments",
    "recordings_from",
    "remove_stale_temp_files",
    "render_playlist",
    "runs_from_segments",
    "slice_types",
]
